version: '3.1'
services:

#Product Service
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
        - "27017:27017"

#Order Service
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_service_db
      MYSQL_USER: order_service_user
      MYSQL_PASSWORD: order_service_user
    ports:
        - "3306:3306"

#Inventory Service
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: inventory_service_db
      POSTGRES_USER: inventory_service_user
      POSTGRES_PASSWORD: inventory_service_user
    ports:
        - "5432:5432"


  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"